CONSTANCE_CONFIG = {
    'TITLE_INDEX_uz': ('Bosh sahifa', 'title'),
    'TITLE_INDEX_ru': ('Главная', 'title'),
    'TITLE_INDEX_en': ('Home', 'title'),
    'MAIN_1_ru': (
        'Наша компания уже много лет обеспечивает население качественными яйцами и куриным мясом. ', 'Header text '),
    'MAIN_1_uz': (
        "Kompaniyamiz ko'p yillardan buyon aholini sifatli tuxum va tovuq go'shti bilan ta'minlab keladi.",
        'Header text '),
    'MAIN_1_en': (
        " Our company has been providing the population with high-quality eggs and chicken meat for many years.",
        'Header text '),
    'MAIN_2_ru': ('НАША ПРОДУКЦИЯ', 'Header button'),
    'MAIN_2_uz': ('BIZNING MAXSULOTLAR', 'Header button'),
    'MAIN_2_en': ('OUR PRODUCTS', 'Header button'),
    'MAIN_3_ru': ('О нас', 'About us'),
    'MAIN_3_uz': ('Biz haqimizda', 'About us'),
    'MAIN_3_en': ('About us', 'About us'),
    'MAIN_4_ru': (
        '«Кушкупир Парранда» - это крупнейшее предприятие в Хорезмской области, обеспечивающий потребителей широкой линейкой высококачественных продуктов.',
        'about us text '),
    'MAIN_4_uz': (
        "«Kushkupir Parranda» Xorazm viloyatidagi eng yirik korxona bo'lib, xaridorlarga yuqori sifatli mahsulotlarni keng assortimenti bilan ta'minlaydi.",
        'about us text '),
    'MAIN_4_en': (
        "«Kushkupir Parranda» is the largest enterprise in the Khorezm region, providing consumers with a wide range of high-quality products.",
        'about us text '),
    'MAIN_5_ru': ('ПОДРОБНЕЕ', 'button'),
    'MAIN_5_uz': ("KO'PROQ O'QING", 'button'),
    'MAIN_5_en': ('READ MORE', 'button'),
    'MAIN_6_ru': ('Мы производим', 'button'),
    'MAIN_6_uz': ('Bizning maxsulotlar', 'button'),
    'MAIN_6_en': ('We produce', 'button'),
    'MAIN_7_ru': ('ЭКСПОРТ И ИМПОРТ', 'button'),
    'MAIN_7_uz': ('EKSPORT VA IMPORT', 'button'),
    'MAIN_7_en': ('EXPORT AND IMPORT', 'button'),
    'MAIN_8_ru': ('ПРОДАЖУ ЯИЦ', 'button'),
    'MAIN_8_uz': ('TUXUMNI SOTISH', 'button'),
    'MAIN_8_en': ('SELL EGGS', 'button'),
    'MAIN_9_ru': ('УЗНАТЬ ПОДРОБНЕЕ', 'button'),
    'MAIN_9_uz': ("KO'PROQ MA'LUMOT OLISH", 'button'),
    'MAIN_9_en': ('LEARN MORE', 'button'),
    'MAIN_10_ru': ('Наши контакты', 'contact'),
    'MAIN_10_uz': ('Biz bilan aloqa', 'contact'),
    'MAIN_10_en': ('Our contacts', 'contact'),
    'MAIN_11_ru': ('Адрес: Республика Узбекистан, Хорезмская область, Кушкупирский район село Узбекяп.', 'address'),
    'MAIN_11_uz': (
        "Manzil: O'zbekiston Respublikasi, Xorazm viloyati, Qushko'pir tumani, O'zbekyap qishlog'i.", 'address'),
    'MAIN_11_en': ('Address: Republic of Uzbekistan, Khorezm region, Kushkupir district, village Uzbekyap.', 'address'),
    'MAIN_12_ru': ('Банк: Хорезмский региональный филиал АК «УзПромстройбанка».', 'Bank info'),
    'MAIN_12_uz': ("Bank: «O'zsanoatqurilishbank» ATB Xorazm viloyati filiali.", 'Bank info'),
    'MAIN_12_en': ("Bank: Khorezm regional branch of JSC «UzPromstroybank».", 'Bank info'),
    'MAIN_13_ru': ('Тел: (+99890)737-00-01.', 'Mobile number'),
    'MAIN_13_uz': ('Tel: (+99890) 737-00-01.', 'Mobile number'),
    'MAIN_13_en': ('Tel: (+99890) 737-00-01.', 'Mobile number'),
    'MAIN_14_ru': ('Мы в соц. сетях:', 'Info social set'),
    'MAIN_14_uz': ('Bizning ijtimoiy tarmoqlarimiz:', 'Info social set'),
    'MAIN_14_en': ('Our socialsets:', 'Info social set'),
    'MAIN_15_ru': ('Все права защищены', 'Last item'),
    'MAIN_15_uz': ('Barcha huquqlar himoyalangan', 'Last item'),
    'MAIN_15_en': ('All rights reserved', 'Last item'),

    'ABOUT_1_ru': (
        'QO’SHKO’PIR PARRANDA - компании которая занимается поставкой яиц, комбикорма,бройлерных цеплят и многого '
        'другого по всему Узбекистану и за границу.',
        'header'),
    'ABOUT_1_uz': (
        "QO’SHKO’PIR PARRANDA - butun O'zbekiston va chet elga tuxum, aralash ozuqa, broyler  va boshqa ko'p narsalarni yetkazib berish bilan shug'ullanadigan kompaniya.",
        'header'),
    'ABOUT_1_en': (
        "QO’SHKO’PIR PARRANDA - a company that is engaged in the supply of eggs, compound feed, broiler hooks and much more throughout Uzbekistan and abroad.",
        'header'),
    'ABOUT_2_ru': ('Мы - лучшие в нашем деле и мы активноразвиваемся и расширяемся с 2004 года.', 'header 2 '),
    'ABOUT_2_uz': (
        "Biz o'z biznesimizdagi eng zo'rimiz va 2004 yildan beri faol rivojlanib va ​​kengayib kelmoqdamiz.",
        'header 2 '),
    'ABOUT_2_en': (
        'We are the best in our business and we have been actively developing and expanding since 2004.', 'header 2 '),
    'TITLE_ABOUT_ru': ('О компании', 'TITLE'),
    'TITLE_ABOUT_uz': ('Kompaniya haqida', 'TITLE'),
    'TITLE_ABOUT_en': ('About', 'TITLE'),
    'ABOUT_3_ru': ('С чего всё начиналось?', 'did  all start'),
    'ABOUT_3_uz': ('Hammasi qanday boshlandi?', 'did  all start'),
    'ABOUT_3_en': ('How did it all begin?', 'did  all start'),
    'ABOUT_4_ru': ('В нынешнее время', 'block'),
    'ABOUT_4_uz': ('Hozirgi vaqtda', 'block'),
    'ABOUT_4_en': ('At the present time', 'block'),
    'ABOUT_5_ru': ('2020 год', 'Title'),
    'ABOUT_5_uz': ('2020 yil', 'Title'),
    'ABOUT_5_en': ('2020 year', 'Title'),
    'ABOUT_6_ru': (
        'В 2020 году на базе птицефабрики был запущен новый завод по переработке мяса птицы его проектная мощность – 1500-2000 голов в час. Процесс производства и убой цыплят-бройлеров отвечают самым высоким международным гигиеническим и техническим стандартам. Также автоматизирована транспортировка птиц из птичника.',
        'Text 1'),
    'ABOUT_6_uz': (
        "2020-yilda parrandachilik fermasi negizida yangi parranda go'shtini qayta ishlash zavodi ishga tushirildi, uning loyihalashtirish quvvati soatiga 1500-2000 boshni tashkil etadi. Broyler tovuqlarini ishlab chiqarish va so'yish jarayoni eng yuqori xalqaro gigiena va texnik standartlarga javob beradi. Uydan qushlarni tashish ham avtomatlashtirilgan.",
        'Text 1'),
    'ABOUT_6_en': (
        'In 2020, a new poultry meat processing plant was launched on the basis of a poultry farm, its project capacity is 1500-2000 heads per hour. The production process and slaughter of broiler chickens meet the highest international hygiene and technical standards. ',
        'Text 1'),
    'ABOUT_7_ru': (
        'Куриное мясо отличается качеством, проходит строгую систему контроля и соответствует требованиям продовольственной безопасности страны. Куры не содержат ГМО, что очень важно для тех, кто заботится о своём здоровье.',
        'text 2'),
    'ABOUT_7_uz': (
        "Tovuq go'shti yuqori sifatli, qattiq nazorat tizimidan o'tgan va mamlakatning oziq-ovqat xavfsizligi talablariga javob beradi. Tovuqlarda GMO mavjud emas, bu ularning sog'lig'iga g'amxo'rlik qiladiganlar uchun juda muhimdir.",
        'text 2'),
    'ABOUT_7_en': (
        'The transportation of birds from the poultry house is also automated. Chicken meat is of high quality, undergoes a strict control system and meets the food safety requirements of the country. Chickens do not contain GMOs, which is very important for those who care about their health.',
        'text 2'),
    'ABOUT_8_ru': ('СВЯЗАТЬСЯ С НАМИ', 'button'),
    'ABOUT_8_uz': ("BIZ BILAN BOG'LANISH", 'button'),
    'ABOUT_8_en': ('CONTACT US', 'button'),
    'ABOUT_9_ru': ('Наши преимущества', 'advantage'),
    'ABOUT_9_uz': ('Bizning afzalliklarimiz', 'advantage'),
    'ABOUT_9_en': ('Our advantages', 'advantage'),

    'TITLE_CATALOG_ru': ('Каталог', 'Title'),
    'TITLE_CATALOG_uz': ('Katalog', 'Title'),
    'TITLE_CATALOG_en': ('Catalog', 'Title'),

    'CATALOG_2_ru': ('Наш каталог', 'Header 1'),
    'CATALOG_2_uz': ('Bizning katalogimiz', 'Header 1'),
    'CATALOG_2_en': ('Our catalog', 'Header 1'),
    'CATALOG_3_ru': (
        'Наши продукты и услуги нашей компании благодаря нашему опыту и качеству могут похвастаться званием лучших в '
        'Узбекистане.',
        'Header 2'),
    'CATALOG_3_uz': (
        "Kompaniyamiz mahsulot va xizmatlari, tajribamiz va sifatimiz tufayli, O'zbekistondagi eng yaxshi degan nom bilan maqtana oladi.",
        'Header 2'),
    'CATALOG_3_en': (
        'Our products and services of our company, thanks to our experience and quality, can boast the title of the best in Uzbekistan.',
        'Header 2'),
    'CATALOG_4_ru': ('НАША ПРОДУКЦИЯ', 'button'),
    'CATALOG_4_uz': ('Bizning ishlab chiqarish', 'button'),
    'CATALOG_4_en': ('OUR PRODUCTION', 'button'),
    'CATALOG_5_ru': ('Мы продаём и доставляем', 'selling'),
    'CATALOG_5_uz': ('Biz sotamiz va etkazib beramiz', 'selling'),
    'CATALOG_5_en': ('We sell and deliver', 'selling'),
    'CATALOG_6_ru': ('Наша продукция - хороший выбор', 'our product'),
    'CATALOG_6_uz': ('Bizning mahsulotlarimiz yaxshi tanlovdir', 'our product'),
    'CATALOG_6_en': ('Our products are a good choice', 'our product'),
    'CATALOG_7_ru': ('Почему же наша продукция хороший выбор?', 'cause of choice '),
    'CATALOG_7_uz': ('Nima uchun bizning mahsulotlarimiz yaxshi tanlovdir?', 'cause of choice '),
    'CATALOG_7_en': ('Why are our products a good choice?', 'cause of choice '),
    'CATALOG_8_ru': (
        'Мы уже более 16 лет на рынке и наша фирма имеет огромный масштаб и мы не хотим на этом останавливаться.',
        'cause of choice'),
    'CATALOG_8_uz': (
        "Biz bozorda 16 yildan buyon faoliyat yuritmoqdamiz va bizning kompaniyamiz katta hajmga ega va biz bu erda to'xtamoqchi emasmiz.",
        'cause of choice'),
    'CATALOG_8_en': (
        'We have been on the market for over 16 years and our company has a huge scale and we do not want to stop there.',
        'cause of choice'),
    'CATALOG_9_ru': (
        'Мы отвечаем за качество товара и мы не голословны (мы вернем вам деньги если будут обнаружены деффекты и так '
        'далее', 'cause of choice'),
    'CATALOG_9_uz': (
        'Biz tovarlarning sifati uchun kafolat beramiz va nuqsonlar aniqlansa pulingizni qaytarib beramiz.',
        'cause of choice'),
    'CATALOG_9_en': (
        'We are responsible for the quality of the goods and we are not unfounded (we will refund your money) if defects are found and so on',
        'cause of choice'),
    'CATALOG_10_ru': ('СВЯЗАТЬСЯ С НАМИ', 'Button'),
    'CATALOG_10_uz': ("BIZ BILAN BOG'LANISH", 'Button'),
    'CATALOG_10_en': ('CONTACT US', 'Button'),

    'CONTACT_TITLE_ru': ('Контакты', 'Title'),
    'CONTACT_TITLE_uz': ('Aloqa uchun', 'Title'),
    'CONTACT_TITLE_en': ('Contacts', 'Title'),
    'CONTACT_1_ru': ('Контакты', 'header 1',),
    'CONTACT_1_uz': ('Aloqa uchun', 'header 1',),
    'CONTACT_1_en': ('Contacts', 'header 1',),
    'CONTACT_2_ru': ('Адрес: Республика Узбекистан, Хорезмская область, Кушкупирский район село Узбекяп.', 'address'),
    'CONTACT_2_uz': (
        "Manzil: O'zbekiston Respublikasi, Xorazm viloyati, Qushko'pir tumani, O'zbekyap qishlog'i.", 'address'),
    'CONTACT_2_en': (
        'Address: Republic of Uzbekistan, Khorezm region, Kushkupir district, village Uzbekyap.', 'address'),
    'CONTACT_3_ru': ('Банк: Хорезмский региональный филиал АК «УзПромстройбанка».', 'header 3'),
    'CONTACT_3_uz': ("Bank: «O'zsanoatqurilishbank» ATB Xorazm viloyati filiali.", 'header 3'),
    'CONTACT_3_en': ("Bank: Khorezm regional branch of JSC «UzPromstroybank».", 'header 3'),
    'CONTACT_4_ru': ('Тел: (+99890)737-00-01.', 'header 4'),
    'CONTACT_4_uz': ('Tel: (+99890) 737-00-01.', 'header 4'),
    'CONTACT_4_en': ('Tel: (+99890) 737-00-01.', 'header 4'),
    'CONTACT_5_ru': ('E-mail: kparranda@mail.ru.', 'header 5'),
    'CONTACT_5_uz': ('E-mail: kparranda@mail.ru.', 'header 5'),
    'CONTACT_5_en': ('E-mail: kparranda@mail.ru.', 'header 5'),
    'CONTACT_6_ru': ('Директор: У.Ю. Мадаминов', 'header 6'),
    'CONTACT_6_uz': ('Direktor: U.Y. Madaminov', 'header 6'),
    'CONTACT_6_en': ('Director: U.Y. Madaminov', 'header 6'),
    'CONTACT_7_ru': ('Оставьте заявку', ' forma title'),
    'CONTACT_7_uz': ("So'rov qoldiring", ' forma title'),
    'CONTACT_7_en': ('Leave a request', ' forma title'),
    'CONTACT_8_ru': ('Имя*', 'forma name'),
    'CONTACT_8_uz': ('Ism*', 'forma name'),
    'CONTACT_8_en': ('Name*', 'forma name'),
    'CONTACT_9_ru': ('Номер телефона*', 'forma mob.number'),
    'CONTACT_9_uz': ('Telefon raqami*', 'forma mob.number'),
    'CONTACT_9_en': ('Phone number*', 'forma mob.number'),
    'CONTACT_10_ru': ('Сообщение*', 'message'),
    'CONTACT_10_uz': ('Xabar*', 'message'),
    'CONTACT_10_en': ('Message*', 'message'),
    'CONTACT_11_ru': ('ОТПРАВИТЬ', 'button'),
    'CONTACT_11_uz': ("JO'NATISH", 'button'),
    'CONTACT_11_en': ('SEND', 'button'),
    'CONTACT_12_ru': (' Сотрудничая с нами вы', 'partner'),
    'CONTACT_12_uz': (' Biz bilan hamkorlik qilsangiz', 'partner'),
    'CONTACT_12_en': (' Cooperating with us you', 'partner'),
    'CONTACT_13_ru': (' Мы находимся', 'karta'),
    'CONTACT_13_uz': (' Bizning manzil', 'karta'),
    'CONTACT_13_en': (' Our address', 'karta'),
    'CONTACT_14_ru': (' Открыть в яндекс карте', 'button'),
    'CONTACT_14_uz': (' Yandex xaritasida ochish', 'button'),
    'CONTACT_14_en': (' Open in Yandex map', 'button'),

    'PARTNER_TITLE_ru': ('Партнёрам', 'Title'),
    'PARTNER_TITLE_uz': ('Hamkorlar', 'Title'),
    'PARTNER_TITLE_en': ('Partners', 'Title'),
    'PARTNER_1_ru': ('Партнёрам', 'Header 1'),
    'PARTNER_1_uz': ('Hamkorlar', 'Header 1'),
    'PARTNER_1_en': ('Partners', 'Header 1'),
    'PARTNER_2_ru': (
        'Наши продукты и услуги нашей компании благодаря нашему опыту и качеству могут похвастаться званием лучших в Узбекистане.',
        'Header 2'),
    'PARTNER_2_uz': (
        "Kompaniyamiz mahsulotlari, xizmatlari, tajribasi va sifatimiz tufayli O'zbekistondagi eng yaxshi degan nomga sazovor bo'lgan.",
        'Header 2'),
    'PARTNER_2_en': (
        'Our company has been named the best in Uzbekistan due to its products, services, experience and quality.',
        'Header 2'),
    'PARTNER_3_ru': ('Тел: (+99890)737-00-01.', 'Header 3'),
    'PARTNER_3_uz': ('Tel: (+99890)737-00-01.', 'Header 3'),
    'PARTNER_3_en': ('Number: (+99890)737-00-01.', 'Header 3'),
    'PARTNER_4_ru': ('E-mail: kparranda@mail.ru.', 'Header 4'),
    'PARTNER_4_uz': ('E-mail: kparranda@mail.ru.', 'Header 4'),
    'PARTNER_4_en': ('E-mail: kparranda@mail.ru.', 'Header 4'),
    'PARTNER_5_ru': ('Директор: У.Ю. Мадаминов', 'Header 5'),
    'PARTNER_5_uz': ('Direktor: U.Y. Madaminov', 'Header 5'),
    'PARTNER_5_en': ('Director: U.Yu. Madaminov', 'Header 5'),
    'PARTNER_6_ru': ('СВЯЗАТЬСЯ С НАМИ', 'button'),
    'PARTNER_6_uz': ("BIZ BILAN BOG'LANISH", 'button'),
    'PARTNER_6_en': ('СВЯЗАТЬСЯ С НАМИ', 'button'),
    'PARTNER_7_ru': ('Преимущества', 'Advantage'),
    'PARTNER_7_uz': ('Foydasi', 'Advantage'),
    'PARTNER_7_en': ('Benefits', 'Advantage'),

    'BASE_1_ru': ('Мы в соц. сетях:', ' '),
    'BASE_1_uz': ('Ijtimoiy tarmoqlar:', ' '),
    'BASE_1_en': ('Our socialsets:', ' '),
    'BASE_2_ru': ('Наш телефон:', ''),
    'BASE_2_uz': ('Telefonimiz:', ''),
    'BASE_2_en': ('Our phone number:', ''),
    'BASE_3_ru': ('Тел: (+99890)737-00-01', ' '),
    'BASE_3_uz': ('Tel: (+99890)737-00-01', ' '),
    'BASE_3_en': ('Number: (+99890)737-00-01', ' '),
    'BASE_4_ru': ('Все права защищены', ' '),
    'BASE_4_uz': ('Huquqlar himoyalangan', ' '),
    'BASE_4_en': ('All rights reserved', ' '),
    'BASE_5_ru': ('2004 - 2020', ' '),
    'BASE_5_uz': ('2004 - 2020', ' '),
    'BASE_5_en': ('2004 - 2020', ' '),
}

CONSTANCE_CONFIG_FIELDSETS = {
    'MainPage': (
        'TITLE_INDEX_ru', 'TITLE_INDEX_uz', 'TITLE_INDEX_en',
        'MAIN_1_ru', 'MAIN_1_uz', 'MAIN_1_en',
        'MAIN_2_ru', 'MAIN_2_uz', 'MAIN_2_en',
        'MAIN_3_ru', 'MAIN_3_uz', 'MAIN_3_en',
        'MAIN_4_ru', 'MAIN_4_uz', 'MAIN_4_en',
        'MAIN_5_ru', 'MAIN_5_uz', 'MAIN_5_en',
        'MAIN_6_ru', 'MAIN_6_uz', 'MAIN_6_en',
        'MAIN_7_ru', 'MAIN_7_uz', 'MAIN_7_en',
        'MAIN_8_ru', 'MAIN_8_uz', 'MAIN_8_en',
        'MAIN_9_ru', 'MAIN_9_uz', 'MAIN_9_en',
        'MAIN_10_ru', 'MAIN_10_uz', 'MAIN_10_en',
        'MAIN_11_ru', 'MAIN_11_uz', 'MAIN_11_en',
        'MAIN_12_ru', 'MAIN_12_uz', 'MAIN_12_en',
        'MAIN_13_ru', 'MAIN_13_uz', 'MAIN_13_en',
        'MAIN_14_ru', 'MAIN_14_uz', 'MAIN_14_en',
        'MAIN_15_ru', 'MAIN_15_uz', 'MAIN_15_en',
    ),

    'AboutPage': (
        "ABOUT_1_ru", "ABOUT_1_uz", "ABOUT_1_en",
        "ABOUT_2_ru", "ABOUT_2_uz", "ABOUT_2_en",
        "ABOUT_3_ru", "ABOUT_3_uz", "ABOUT_3_en",
        "ABOUT_4_ru", "ABOUT_4_uz", "ABOUT_4_en",
        "ABOUT_5_ru", "ABOUT_5_uz", "ABOUT_5_en",
        "ABOUT_6_ru", "ABOUT_6_uz", "ABOUT_6_en",
        "ABOUT_7_ru", "ABOUT_7_uz", "ABOUT_7_en",
        "ABOUT_8_ru", "ABOUT_8_uz", "ABOUT_8_en",
        "ABOUT_9_ru", "ABOUT_9_uz", "ABOUT_9_en",
        "TITLE_ABOUT_ru", "TITLE_ABOUT_uz", "TITLE_ABOUT_en",
    ),

    'CatalogPage': (
        'TITLE_CATALOG_ru', 'TITLE_CATALOG_uz', 'TITLE_CATALOG_en',
        'CATALOG_2_ru', 'CATALOG_2_uz', 'CATALOG_2_en',
        'CATALOG_3_ru', 'CATALOG_3_uz', 'CATALOG_3_en',
        'CATALOG_4_ru', 'CATALOG_4_uz', 'CATALOG_4_en',
        'CATALOG_5_ru', 'CATALOG_5_uz', 'CATALOG_5_en',
        'CATALOG_6_ru', 'CATALOG_6_uz', 'CATALOG_6_en',
        'CATALOG_7_ru', 'CATALOG_7_uz', 'CATALOG_7_en',
        'CATALOG_8_ru', 'CATALOG_8_uz', 'CATALOG_8_en',
        'CATALOG_9_ru', 'CATALOG_9_uz', 'CATALOG_9_en',
        'CATALOG_10_ru', 'CATALOG_10_uz', 'CATALOG_10_en',
    ),
    'ContactPage': (
        'CONTACT_TITLE_ru', 'CONTACT_TITLE_uz', 'CONTACT_TITLE_en',
        'CONTACT_1_ru', 'CONTACT_1_uz', 'CONTACT_1_en',
        'CONTACT_2_ru', 'CONTACT_2_uz', 'CONTACT_2_en',
        'CONTACT_3_ru', 'CONTACT_3_uz', 'CONTACT_3_en',
        'CONTACT_4_ru', 'CONTACT_4_uz', 'CONTACT_4_en',
        'CONTACT_5_ru', 'CONTACT_5_uz', 'CONTACT_5_en',
        'CONTACT_6_ru', 'CONTACT_6_uz', 'CONTACT_6_en',
        'CONTACT_7_ru', 'CONTACT_7_uz', 'CONTACT_7_en',
        'CONTACT_8_ru', 'CONTACT_8_uz', 'CONTACT_8_en',
        'CONTACT_9_ru', 'CONTACT_9_uz', 'CONTACT_9_en',
        'CONTACT_10_ru', 'CONTACT_10_uz', 'CONTACT_10_en',
        'CONTACT_11_ru', 'CONTACT_11_uz', 'CONTACT_11_en',
        'CONTACT_12_ru', 'CONTACT_12_uz', 'CONTACT_12_en',
        'CONTACT_13_ru', 'CONTACT_13_uz', 'CONTACT_13_en',
        'CONTACT_14_ru', 'CONTACT_14_uz', 'CONTACT_14_en',
    ),
    'PartnerPage': (
        'PARTNER_TITLE_ru', 'PARTNER_TITLE_uz', 'PARTNER_TITLE_en',
        'PARTNER_1_ru', 'PARTNER_1_uz', 'PARTNER_1_en',
        'PARTNER_2_ru', 'PARTNER_2_uz', 'PARTNER_2_en',
        'PARTNER_3_ru', 'PARTNER_3_uz', 'PARTNER_3_en',
        'PARTNER_4_ru', 'PARTNER_4_uz', 'PARTNER_4_en',
        'PARTNER_5_ru', 'PARTNER_5_uz', 'PARTNER_5_en',
        'PARTNER_6_ru', 'PARTNER_6_uz', 'PARTNER_6_en',
        'PARTNER_7_ru', 'PARTNER_7_uz', 'PARTNER_7_en',
    ),
    'BaseSite': (
        'BASE_1_ru', 'BASE_1_uz', 'BASE_1_en',
        'BASE_2_ru', 'BASE_2_uz', 'BASE_2_en',
        'BASE_3_ru', 'BASE_3_uz', 'BASE_3_en',
        'BASE_4_ru', 'BASE_4_uz', 'BASE_4_en',
        'BASE_5_ru', 'BASE_5_uz', 'BASE_5_en',
    ),

}
#
# CONSTANCE_CONFIG_FIELDSETS = {
#     'Main Page Items': {
#         'fields': (
#             'TITLE_INDEX_ru', 'TITLE_INDEX_uz', 'TITLE_INDEX_en',
#             'MAIN_1_ru', 'MAIN_1_uz', 'MAIN_1_en',
#             'MAIN_2_ru', 'MAIN_2_uz', 'MAIN_2_en',
#             'MAIN_3_ru', 'MAIN_3_uz', 'MAIN_3_en',
#             'MAIN_4_ru', 'MAIN_4_uz', 'MAIN_4_en',
#             'MAIN_5_ru', 'MAIN_5_uz', 'MAIN_5_en',
#             'MAIN_6_ru', 'MAIN_6_uz', 'MAIN_6_en',
#             'MAIN_7_ru', 'MAIN_7_uz', 'MAIN_7_en',
#             'MAIN_8_ru', 'MAIN_8_uz', 'MAIN_8_en',
#             'MAIN_9_ru', 'MAIN_9_uz', 'MAIN_9_en',
#             'MAIN_10_ru', 'MAIN_10_uz', 'MAIN_10_en',
#             'MAIN_11_ru', 'MAIN_11_uz', 'MAIN_11_en',
#             'MAIN_12_ru', 'MAIN_12_uz', 'MAIN_12_en',
#             'MAIN_13_ru', 'MAIN_13_uz', 'MAIN_13_en',
#             'MAIN_14_ru', 'MAIN_14_uz', 'MAIN_14_en',
#             'MAIN_15_ru', 'MAIN_15_uz', 'MAIN_15_en',
#         ),
#         'collapse': True
#     },
#     'Abouts Page Items': {
#         'fields': (
#             "ABOUT_1_ru", "ABOUT_1_uz", "ABOUT_1_en",
#             "ABOUT_2_ru", "ABOUT_2_uz", "ABOUT_2_en",
#             "ABOUT_3_ru", "ABOUT_3_uz", "ABOUT_3_en",
#             "ABOUT_4_ru", "ABOUT_4_uz", "ABOUT_4_en",
#             "ABOUT_5_ru", "ABOUT_5_uz", "ABOUT_5_en",
#             "ABOUT_6_ru", "ABOUT_6_uz", "ABOUT_6_en",
#             "ABOUT_7_ru", "ABOUT_7_uz", "ABOUT_7_en",
#             "ABOUT_8_ru", "ABOUT_8_uz", "ABOUT_8_en",
#             "ABOUT_9_ru", "ABOUT_9_uz", "ABOUT_9_en",
#             "TITLE_ABOUT_ru", "TITLE_ABOUT_uz", "TITLE_ABOUT_en",
#         ),
#         'collapse': True
#     },
#     'Catalog Page Items': {
#         'fields': (
#             'TITLE_CATALOG_ru', 'TITLE_CATALOG_uz', 'TITLE_CATALOG_en',
#             'CATALOG_2_ru', 'CATALOG_2_uz', 'CATALOG_2_en',
#             'CATALOG_3_ru', 'CATALOG_3_uz', 'CATALOG_3_en',
#             'CATALOG_4_ru', 'CATALOG_4_uz', 'CATALOG_4_en',
#             'CATALOG_5_ru', 'CATALOG_5_uz', 'CATALOG_5_en',
#             'CATALOG_6_ru', 'CATALOG_6_uz', 'CATALOG_6_en',
#             'CATALOG_7_ru', 'CATALOG_7_uz', 'CATALOG_7_en',
#             'CATALOG_8_ru', 'CATALOG_8_uz', 'CATALOG_8_en',
#             'CATALOG_9_ru', 'CATALOG_9_uz', 'CATALOG_9_en',
#             'CATALOG_10_ru', 'CATALOG_10_uz', 'CATALOG_10_en',
#         ),
#         'collapse': True
#     },
#     'Contact Page Items': {
#         'fields': (
#             'CONTACT_TITLE_ru', 'CONTACT_TITLE_uz', 'CONTACT_TITLE_en',
#             'CONTACT_1_ru', 'CONTACT_1_uz', 'CONTACT_1_en',
#             'CONTACT_2_ru', 'CONTACT_2_uz', 'CONTACT_2_en',
#             'CONTACT_3_ru', 'CONTACT_3_uz', 'CONTACT_3_en',
#             'CONTACT_4_ru', 'CONTACT_4_uz', 'CONTACT_4_en',
#             'CONTACT_5_ru', 'CONTACT_5_uz', 'CONTACT_5_en',
#             'CONTACT_6_ru', 'CONTACT_6_uz', 'CONTACT_6_en',
#             'CONTACT_7_ru', 'CONTACT_7_uz', 'CONTACT_7_en',
#             'CONTACT_8_ru', 'CONTACT_8_uz', 'CONTACT_8_en',
#             'CONTACT_9_ru', 'CONTACT_9_uz', 'CONTACT_9_en',
#             'CONTACT_10_ru', 'CONTACT_10_uz', 'CONTACT_10_en',
#             'CONTACT_11_ru', 'CONTACT_11_uz', 'CONTACT_11_en',
#             'CONTACT_12_ru', 'CONTACT_12_uz', 'CONTACT_12_en',
#             'CONTACT_13_ru', 'CONTACT_13_uz', 'CONTACT_13_en',
#             'CONTACT_14_ru', 'CONTACT_14_uz', 'CONTACT_14_en',
#         ),
#         'collapse': True
#     },
#     'Partner Page Items': {
#         'fields': (
#             'PARTNER_TITLE_ru', 'PARTNER_TITLE_uz', 'PARTNER_TITLE_en',
#             'PARTNER_1_ru', 'PARTNER_1_uz', 'PARTNER_1_en',
#             'PARTNER_2_ru', 'PARTNER_2_uz', 'PARTNER_2_en',
#             'PARTNER_3_ru', 'PARTNER_3_uz', 'PARTNER_3_en',
#             'PARTNER_4_ru', 'PARTNER_4_uz', 'PARTNER_4_en',
#             'PARTNER_5_ru', 'PARTNER_5_uz', 'PARTNER_5_en',
#             'PARTNER_6_ru', 'PARTNER_6_uz', 'PARTNER_6_en',
#             'PARTNER_7_ru', 'PARTNER_7_uz', 'PARTNER_7_en',
#         ),
#         'collapse': True
#     },
#     'Base Items': {
#         'fields': (
#             'BASE_1_ru', 'BASE_1_uz', 'BASE_1_en',
#             'BASE_2_ru', 'BASE_2_uz', 'BASE_2_en',
#             'BASE_3_ru', 'BASE_3_uz', 'BASE_3_en',
#             'BASE_4_ru', 'BASE_4_uz', 'BASE_4_en',
#             'BASE_5_ru', 'BASE_5_uz', 'BASE_5_en',
#         ),
#         'collapse': True
#     },
#
# }
