"""
Django settings for qp_chorva project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path
from django.contrib.messages import constants as messages
from constance.signals import config_updated

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '55ifs^m32)r%$)q-wyh=s1jgw1+=$xl+)ck+7=97oqo@kc0^g('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'constance',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'appmain',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'qp_chorva.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'constance.context_processors.config',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'appmain.context_processors.myview',
            ],
        },
    },
]

WSGI_APPLICATION = 'qp_chorva.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)
CONSTANCE_BACKEND = 'constance.backends.redisd.RedisBackend'

CONSTANCE_REDIS_CONNECTION = {
    'host': 'localhost',
    'port': 6379,
    'db': 0,
}

CONSTANCE_CONFIG = {

    'MAIN_1': (
        'Мы - проект и занимаемся нашим делом уже очень давномы производим то-то то-то уже в течении 032035 лет и мы '
        'лучшие на рынке среди наших конкурентов. ',
        'Header text '),
    'MAIN_2': ('НАША ПРОДУКЦИЯ', 'Header button'),
    'MAIN_3': ('О нас', 'About us'),
    'MAIN_4': (
        'Мы - проект и занимаемся нашим делом уже очень давномы производим то-то то-то уже в течении 032035 лет и мы '
        'лучшие на рынке среди наших конкурентов.',
        'about us text',),
    'MAIN_5': ('ПОДРОБНЕЕ', 'button'),
    'MAIN_6': ('Мы производим', 'button'),
    'MAIN_7': ('ЭКСПОРТ И ИМПОРТ', 'button'),
    'MAIN_8': ('ПРОДАЖУ ЯИЦ', 'button'),
    'MAIN_9': ('УЗНАТЬ ПОДРОБНЕЕ', 'button'),
    'MAIN_10': ('Наши контакты', 'contact'),
    'MAIN_11': ('Адрес: Республика Узбекистан, Хорезмская область, Кушкупирский район село Узбекяп.', 'address'),
    'MAIN_12': ('Банк: Хорезмский региональный филиал АК «УзПромстройбанка».', 'Bank info'),
    'MAIN_13': ('Тел: (+99890)737-00-01.', 'Mobile number'),
    'MAIN_14': ('Мы в соц. сетях:', 'Info social set'),
    'MAIN_15': ('Все права защищены', 'Last item'),

    "ABOUT_1": (
        'QO’SHKO’PIR PARRANDA - компании которая занимается поставкой яиц, комбикорма,бройлерных цеплят и многого '
        'другого по всему Узбекистану и за границу.',
        'header'),
    "ABOUT_2": ('Мы - лучшие в нашем деле и мы активноразвиваемся и расширяемся с 2004 года.', 'header 2 '),
    "TITLE_A": ('О компании', 'TITLE'),
    "ABOUT_3": ('С чего всё начиналось?', 'did  all start'),
    "ABOUT_4": ('В нынешнее время', 'block'),
    "ABOUT_5": ('2020 год', 'Title'),
    "ABOUT_6": (
        'Убой бройлерных кур (1500-2000) голов и захват рынка, поставки за границу и расширение наших границ.',
        'Text 1'),
    "ABOUT_7": (
        'Мы - компания с долгой историей развития и нам вы можете доверять. Мы отвечаем за качество нашего продукта.',
        'text 2'),
    "ABOUT_8": ('СВЯЗАТЬСЯ С НАМИ', 'button'),
    "ABOUT_9": ('Наши преимущества', 'advantage'),

}

# CONSTANCE_CONFIG_FIELDSETS = {
#     'Main page': {
#         'fields': (
#             'MAIN_1', 'MAIN_2', 'MAIN_3', 'MAIN_4', 'MAIN_5', 'MAIN_6', 'MAIN_7', 'MAIN_8', 'MAIN_9', 'MAIN_10',
#             'MAIN_11',
#             'MAIN_12', 'MAIN_13',
#         ),
#         'collapse': True
#     },
#
# }

CONSTANCE_CONFIG_FIELDSETS = {
    'MainPage': (
        'MAIN_1', 'MAIN_2', 'MAIN_3', 'MAIN_4', 'MAIN_5', 'MAIN_6', 'MAIN_7', 'MAIN_8', 'MAIN_9', 'MAIN_10', 'MAIN_11',
        'MAIN_12', 'MAIN_13', 'MAIN_14', 'MAIN_15',),
    'AboutPage': (
        "ABOUT_1", "ABOUT_2", "ABOUT_3", "ABOUT_4", "ABOUT_5", "ABOUT_6", "ABOUT_7", "ABOUT_8", "ABOUT_9", "TITLE_A",),
}
