"""
Django settings for qp_chorva project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path
from django.contrib.messages import constants as messages
from constance.signals import config_updated

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '55ifs^m32)r%$)q-wyh=s1jgw1+=$xl+)ck+7=97oqo@kc0^g('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'constance',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'appmain',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'qp_chorva.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'constance.context_processors.config',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'appmain.context_processors.myview',
            ],
        },
    },
]

WSGI_APPLICATION = 'qp_chorva.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)
CONSTANCE_BACKEND = 'constance.backends.redisd.RedisBackend'

CONSTANCE_REDIS_CONNECTION = {
    'host': 'localhost',
    'port': 6379,
    'db': 0,
}

CONSTANCE_CONFIG = {

    'MAIN_1': (
        'Мы - проект и занимаемся нашим делом уже очень давномы производим то-то то-то уже в течении 032035 лет и мы '
        'лучшие на рынке среди наших конкурентов. ',
        'Header text '),
    'MAIN_2': ('НАША ПРОДУКЦИЯ', 'Header button'),
    'MAIN_3': ('О нас', 'About us'),
    'MAIN_4': (
        'Мы - проект и занимаемся нашим делом уже очень давномы производим то-то то-то уже в течении 032035 лет и мы '
        'лучшие на рынке среди наших конкурентов.',
        'about us text'),

    'MAIN_6': ('Мы производим', 'button'),
    'MAIN_7': ('ПРОДАЖУ ЯИЦ', 'button'),
    'MAIN_8': ('УЗНАТЬ ПОДРОБНЕЕ', 'button'),
    'MAIN_9': ('Наши контакты', 'contact'),
    'MAIN_10': ('Банк: Хорезмский региональный филиал АК «УзПромстройбанка».', 'Bank info'),
    'MAIN_11': ('Тел: (+99890)737-00-01.', 'Mobile number'),
    'MAIN_12': ('Мы в соц. сетях:', 'Info social set'),
    'MAIN_13': ('Все права защищены', 'last item'),
    'MAIN_14': ('ПОДРОБНЕЕ', 'button'),
}

# CONSTANCE_CONFIG_FIELDSETS = {
#     'MainPage': ('MAIN_1', 'MAIN_2', 'MAIN_3', 'MAIN_4', 'MAIN_5', 'MAIN_6', 'MAIN_7', 'MAIN_8',),
#
# }

CONSTANCE_CONFIG_FIELDSETS = {
    'Main page': {
        'fields': (
            'MAIN_1', 'MAIN_2', 'MAIN_3', 'MAIN_4', 'MAIN_6', 'MAIN_7', 'MAIN_8', 'MAIN_9', 'MAIN_10',
            'MAIN_11',
            'MAIN_12', 'MAIN_13', 'MAIN_14'),
        'collapse': True
    },

}
