# Generated by Django 3.1.3 on 2020-11-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('img', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('show', models.BooleanField(default=True)),
            ],
        ),
    ]
