# Generated by Django 3.1.3 on 2020-11-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='about_page', verbose_name='image 1')),
                ('image_background', models.ImageField(blank=True, upload_to='about_page2', verbose_name='image 2')),
                ('show', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'статья: о компании',
                'verbose_name_plural': 'статьи:о компании',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='CatalogPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='catalog_image')),
                ('text_1', models.CharField(blank=True, max_length=100)),
                ('text_2', models.CharField(blank=True, max_length=100)),
                ('text_3', models.CharField(blank=True, max_length=100)),
                ('text_4', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'статья:каталог',
                'verbose_name_plural': 'статьи:каталог',
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='contact-page')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'статья:контакт',
                'verbose_name_plural': 'статьи:контакты',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='имя отправителя сообщения')),
                ('number', models.IntegerField()),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'заявку',
                'verbose_name_plural': 'заявкы',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OurAdvantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('image_2', models.ImageField(upload_to='about_page', verbose_name='main image')),
                ('image', models.ImageField(blank=True, upload_to='about_page', verbose_name='image')),
            ],
            options={
                'verbose_name': 'статья: наше преимущество',
                'verbose_name_plural': 'статьи:наши преимущества',
            },
        ),
        migrations.CreateModel(
            name='PartnerPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=100)),
                ('image_background', models.ImageField(upload_to='partner_image')),
                ('image', models.ImageField(blank=True, upload_to='partner_image')),
            ],
            options={
                'verbose_name': 'статья:партнёр',
                'verbose_name_plural': 'статьи:партнёр',
            },
        ),
    ]
