# Generated by Django 3.1.3 on 2020-11-05 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name of sender')),
                ('number', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'send request',
                'verbose_name_plural': 'snd requests',
            },
        ),
        migrations.DeleteModel(
            name='Connetcion',
        ),
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'ordering': ['-created_date'], 'verbose_name': 'Add post about page', 'verbose_name_plural': 'Add posts about page'},
        ),
        migrations.AlterModelOptions(
            name='contactpage',
            options={'ordering': ['-created_date'], 'verbose_name': 'Add post contact page', 'verbose_name_plural': 'Add posts contact page'},
        ),
    ]
