# Generated by Django 3.1.3 on 2020-11-09 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0002_auto_20201108_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
    ]
