# Generated by Django 3.1.3 on 2020-11-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0002_auto_20201104_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcompany',
            name='image',
            field=models.ImageField(blank=True, upload_to='about_page'),
        ),
        migrations.AlterField(
            model_name='aboutcompany',
            name='image_background',
            field=models.ImageField(blank=True, upload_to='about_page2'),
        ),
    ]
