# Generated by Django 3.1.3 on 2020-11-09 19:04

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0003_auto_20201109_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('key_ru', models.CharField(max_length=255, null=True, unique=True)),
                ('key_uz', models.CharField(max_length=255, null=True, unique=True)),
                ('key_en', models.CharField(max_length=255, null=True, unique=True)),
                ('value', picklefield.fields.PickledObjectField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'constance',
                'verbose_name_plural': 'constances',
                'db_table': 'constance_config',
            },
        ),
    ]
