# Generated by Django 3.1.3 on 2020-11-09 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0004_constance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Constance',
        ),
    ]
