# Generated by Django 3.1.3 on 2020-11-05 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0004_auto_20201105_1000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'contac us', 'verbose_name_plural': 'contac us'},
        ),
    ]
