# Generated by Django 3.1.3 on 2020-11-05 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0005_auto_20201105_1000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'contact us', 'verbose_name_plural': 'contact us'},
        ),
    ]
