# Generated by Django 3.1.3 on 2020-11-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0006_auto_20201105_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=100)),
                ('image_background', models.ImageField(blank=True, upload_to='partner_image')),
                ('image', models.ImageField(blank=True, upload_to='partner_image')),
            ],
            options={
                'verbose_name': 'add post to partner page',
                'verbose_name_plural': 'add posts to partner page',
            },
        ),
        migrations.AlterField(
            model_name='contactus',
            name='number',
            field=models.IntegerField(),
        ),
    ]
