# Generated by Django 3.1.3 on 2020-11-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0007_auto_20201105_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerpage',
            name='image_background',
            field=models.ImageField(upload_to='partner_image'),
        ),
    ]
