# Generated by Django 3.1.3 on 2020-11-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0008_auto_20201105_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurAdvantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='about_page', verbose_name='image')),
                ('image_2', models.ImageField(blank=True, upload_to='about_page', verbose_name='images')),
            ],
            options={
                'verbose_name': 'пост: наше преимущество',
                'verbose_name_plural': 'посты:наши преимущества',
            },
        ),
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'ordering': ['-created_date'], 'verbose_name': 'пост: о компании', 'verbose_name_plural': 'посты:о компании'},
        ),
        migrations.AlterModelOptions(
            name='contactpage',
            options={'ordering': ['-created_date'], 'verbose_name': 'пост:контакт', 'verbose_name_plural': 'посты:контакты'},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'заявку', 'verbose_name_plural': 'заявкы'},
        ),
        migrations.AlterModelOptions(
            name='partnerpage',
            options={'verbose_name': 'пост:партнёр', 'verbose_name_plural': 'посты:партнёр'},
        ),
    ]
